version: '3.6'

services:
  rabbitmq:
    image: rabbitmq:3.7.6-management
    restart: always
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./configurations/:/etc/rabbitmq/
    ports:
      - 5672:5672
      - 15672:15672
volumes:
  rabbitmq_data:
