version: '2'

services:
  redis:
   image: 'redis:7.0'
   restart: always 
   container_name: Redis-Server
   environment:
      - ALLOW_EMPTY_PASSWORD=yes
   ports:
      - "6379:6379"
   volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
      - ./cache:/data
   entrypoint: redis-server /usr/local/etc/redis/redis.conf
   deploy:
       resources:
           limits:
             memory: 2048M
           reservations:
             memory: 1024M

